apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-names-backend
  labels:
    app: contoso-names-backend
  namespace: contoso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contoso-names-backend
  template:
    metadata:
      labels:
        app: contoso-names-backend
    spec:
      containers:
        - name: contoso-names-backend
          image: contosoacrbuild.azurecr.io/contoso-names-backend:latest
          ports:
            - containerPort: 80