apiVersion: v1
kind: Service
metadata:
  name: contosonames-service
  namespace: contoso
spec:
  type: LoadBalancer
  selector:
    app: contosonames-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80